<a href="https://colab.research.google.com/github/ldperez/tributePage/blob/master/LuisPerez_Assignment_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.1. Predicting Student Recommendation:**

1.1.1. Download the student_records.csv file (located in your assignment prompt in Blackboard).

1.1.2. Run all codes on the example in the lecture, Textbook 1 – Chapter 1:

Page 19-28 and Page55-64.

The goal is to build a predictive model based on the dataset. The model can predict for
any future student if they will be recommended for the grant based on their performance
attributes.

1.1.3. Write down your understanding about the codes and each part’s functioning.


Vector (pg 19)


In [ ]:
x = [1, 2, 3, 4, 5]
x

[1, 2, 3, 4, 5]

A defined array where the arrangement or order matters. 

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


print array and print type of array

Matrix (pg19-20)

In [ ]:
m = np.array([[1, 5, 2],[4, 7, 4],[2, 0, 9]])


# view matrix
print(m)

 # view dimensions
print(m.shape)


[[1 5 2]
 [4 7 4]
 [2 0 9]]
(3, 3)


Define matrix using an array, then print the array and shape

In [ ]:
# matrix transpose
print('Matrix Transpose:\n', m.transpose(), '\n')

# matrix determinant
print ('Matrix Determinant:', np.linalg.det(m), '\n')

# matrix inverse
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

# identity matrix (result of matrix x matrix_inverse)
iden_m = np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)
print ('Product of matrix and its inverse:\n', iden_m)

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 

Matrix Determinant: -105.00000000000006 

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


matrix operations transpose, determinants,  and result of matrix inverse

Eigen Decomposition pg (21)

In [ ]:
# eigendecomposition
m = np.array([[1, 5, 2],
[4, 7, 4],
[2, 0, 9]])

eigen_vals, eigen_vecs = np.linalg.eig(m)

print('Eigen Values:', eigen_vals, '\n')
print('Eigen Vectors:\n', eigen_vecs)


Eigen Values: [-1.32455532 11.32455532  7.        ] 

Eigen Vectors:
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


Matrix decomposition/ break down into a set of eight vectors and eigen values.

M = V diag(λ) V-1 

Mv = λv where M is our matrix, v is the eigen vector and λ is the corresponding eigen value. 


**Singular Value Decomposition (pg22)**

In [ ]:
# SVD
m = np.array([[1, 5, 2],
[4, 7, 4],
[2, 0, 9]])

U, S, VT = np.linalg.svd(m)

print('Getting SVD outputs:-\n')
print('U:\n', U, '\n')
print('S:\n', S, '\n')
print('VT:\n', VT, '\n')


Getting SVD outputs:-

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



Matrix decomposition to get singular vectors and singular values.

U and V will always be orthogonal


**Statistics (pg 24)**

In [ ]:
 # descriptive statistics
import scipy as sp
import numpy as np
from scipy import stats
# get data
nums = np.random.randint(1,20, size=(1,15))[0]
print('Data: ', nums)

# get descriptive stats
print ('Mean:', sp.mean(nums))
print ('Median:', sp.median(nums))
print ('Mode:', sp.stats.mode(nums))
print ('Standard Deviation:', sp.std(nums))
print ('Variance:', sp.var(nums))
print ('Skew:', sp.stats.skew(nums))
print ('Kurtosis:', sp.stats.kurtosis(nums))

Data:  [14 19  6  1 11  9  5  4 10 12 16  1  7  7 10]
Mean: 8.8
Median: 9.0
Mode: ModeResult(mode=array([1]), count=array([2]))
Standard Deviation: 4.995998398718719
Variance: 24.96
Skew: 0.25327962789362296
Kurtosis: -0.5815869493754122


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  


Python library scipy, descriptive statistics can give the mean, mode, median,skewness, kurtosis, standard deviation, variance, etc.

Other similar libraries and frameworks: pandas, numpy


In [ ]:
import matplotlib.pyplot as plt
from nltk.parse.stanford import StanfordParser
import numpy as np

%matplotlib inline

sentence = 'The quick brown fox jumps over the lazy dog'

# create parser object
scp = StanfordParser(path_to_jar='/content/stanford-parser.jar', 
 path_to_models_jar='stanford-parser-4.2.0-models.jar')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: The StanfordParser will be deprecated
Please use nltk.parse.corenlp.CoreNLPParser instead.
  # This is added back by InteractiveShellApp.init_path()


import the stanford parser, create a sentence to be analyzed, create parser object

In [ ]:
# get parse tree
result = list(scp.raw_parse(sentence)) 
tree = result[0]

# print the constituency parse tree
print(tree)


(ROOT
  (S
    (NP (DT The) (JJ quick) (JJ brown) (NN fox))
    (VP (VBZ jumps) (PP (IN over) (NP (DT the) (JJ lazy) (NN dog))))))


run the sentence through parser, print constituency tree

In [ ]:
!apt-get install -y xvfb 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
xvfb is already the newest version (2:1.19.6-1ubuntu4.10).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.


In [ ]:
import os
os.system("Xvfb :1 -screen 0 720x720x16 &")
os.environ['DISPLAY'] = ":1.0"

In [ ]:
%matplotlib inline
#visualize constituency parse tree
#tree.draw()
from IPython.core.display import Image

Image('tree.png')

This would save the parser tree then call it to display but since google collab is a virtual computer we had to go around this. solution takes too long to display. 

**Predicting Student Recommendation (pg 55-64).**

In [ ]:
import pandas as pd
# turn of warning messages
pd.options.mode.chained_assignment = None # default='warn'

# get data
df = pd.read_csv('student_records.csv')
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

We start by retrieving data from a csv using pandas. 


**Feature Extraction and Engineering**





In [ ]:
# get features and corresponding outcomes
feature_names = ['OverallGrade', 'Obedient', 'ResearchScore','ProjectScore']
training_features = df[feature_names]
outcome_name = ['Recommend']
outcome_labels = df[outcome_name]

# view features
training_features


OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33

Separate the features from the outcome

In [ ]:
# view outcome labels
outcome_labels

Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No

print outcome levels

In [ ]:
# list down features based on type
numeric_feature_names = ['ResearchScore', 'ProjectScore']
categoricial_feature_names = ['OverallGrade', 'Obedient']

separating the categorical values from numeric

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

# fit scaler on numeric features
ss.fit(training_features[numeric_feature_names])
 
# scale numeric features now
training_features[numeric_feature_names] =ss.transform(training_features[numeric_feature_names])
 
# view updated featureset
training_features

OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y       0.899583      1.376650
1            C        N       0.730648     -0.091777
2            F        N      -1.803390     -1.560203
3            B        Y       0.392776      0.772004
4            E        N      -1.465519     -0.998746
5            A        Y       0.967158      1.117516
6            B        Y      -0.114032      0.253735
7            C        Y       0.392776     -0.869179

Use scikit-learn to (standard scalar) to scale/normalize numeric attributes 

In [ ]:
training_features = pd.get_dummies(training_features, columns=categoricial_feature_names)

# view newly engineering features
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

Use Dummy variables to transform categorical values into numeric.

**Modeling**

In [ ]:
# get list of new categorical features
categorical_engineered_features = list(set(training_features.columns) -
 set(numeric_feature_names))

list of new categorical features

In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# fit the model
lr = LogisticRegression()
model = lr.fit(training_features, np.array(outcome_labels['Recommend']))

# view model parameters
model

LogisticRegression(C=1.0, class_weight=None, dual=False,
 fit_intercept=True, intercept_scaling=1, max_iter=100,
multi_class='ovr', n_jobs=1, penalty='l2',
random_state=None, solver='liblinear', tol=0.0001,
verbose=0, warm_start=False)

LogisticRegression(multi_class='ovr', n_jobs=1, solver='liblinear')

classification model using logistic regression


**Model Evaluation**

In [ ]:
 # simple evaluation on training data
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['Recommend'])

# evaluate model performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
 
print('Accuracy:', float(accuracy_score(actual_labels,
pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))

Accuracy: 100.0 %
Classification Stats:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         5
         Yes       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



Use training data to evaluate predictive levels of model

Evaluate the model performance using sklearn.metrics  accuracy_score and classification_report 

Print results to visualize results in an easy-to-see manner



**Model Deployment**





In [ ]:
import joblib
import os

# save models to be deployed on your server
if not os.path.exists('Model'):
  os.mkdir('Model')
if not os.path.exists('Scaler'):
  os.mkdir('Scaler')

joblib.dump(model, r'Model/model.pickle')
joblib.dump(ss, r'Scaler/scaler.pickle')


['Scaler/scaler.pickle']

To deploy the model we need a way to store the model and scalar objects

One way is to use sklearn.externals and import joblib this will allow to use new data samples and reload the model.


**Prediction in Action **

In [ ]:
# load model and scaler objects
model = joblib.load(r'Model/model.pickle')
scaler = joblib.load(r'Scaler/scaler.pickle')


Load model and scalar objects

In [ ]:
## data retrieval
new_data = pd.DataFrame([{'Name': 'Nathan', 'OverallGrade': 'F',
 'Obedient': 'N', 'ResearchScore': 30, 'ProjectScore': 20},
{'Name': 'Thomas', 'OverallGrade': 'A',
 'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
new_data = new_data[['Name', 'OverallGrade', 'Obedient',
 'ResearchScore', 'ProjectScore']]
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

Feed a new sample of students to test the model

Load a new dataframe with new information

Load labels so data can match


**Data Preparation**

In [ ]:
## data preparation
prediction_features = new_data[feature_names]

 # scaling
prediction_features[numeric_feature_names] = scaler.transform(prediction_features[numeric_feature_names])

 # engineering categorical variables
prediction_features = pd.get_dummies(prediction_features, columns=categoricial_feature_names)

 # view feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  
0           0  
1           1

Prepare the data (—feature extraction, engineering, and scaling) to match the previous data

**missing categorical features**


In [ ]:
# add missing categorical feature columns
current_categorical_engineered_features =set(prediction_features.columns) - set(numeric_feature_names)
 
missing_features = set(categorical_engineered_features) -current_categorical_engineered_features

#add zeros since feature is absent in these data samples
for feature in missing_features:
  prediction_features[feature] = [0] * len(prediction_features)

# view final feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  OverallGrade_E  OverallGrade_C  OverallGrade_B  
0           0               0               0               0  
1           1               0               0               0

In this case, data was missing some values since we used Dummy variables in the original data.

Add zero to missing values due to dummy variables
Start using model to predict




**get the predictions**

In [ ]:
## predict using model
predictions = model.predict(prediction_features)

## display results
new_data['Recommend'] = predictions
new_data

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Nathan            F        N             30            20        No
1  Thomas            A        Y             78            80       Yes

run the predictive model and

Display results

In [98]:
!wget -nc https://raw.githubusercontent.com/brpy/colab-pdf/master/colab_pdf.py
from colab_pdf import colab_pdf
colab_pdf('LuisPerez_Assignment-1.1.ipynb')

File ‘colab_pdf.py’ already there; not retrieving.





[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/LuisPerez_Assignment-1.1.ipynb to pdf
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.7/dist-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.exp

'File Download Unsuccessful. Saved in Google Drive'

This code saves the file as .ipynb and transforms it into a PDF in google drive